### ISSUE TITLE
The player sticks to the sides of any object while in air

### ISSUE THREAD

**Issue by YeDemirkiran** [zamcham/scalatic-escape#4]
- It sticks to the side of an object when the player is pressing the corresponding key of the side the player is touching with. If the player is touching with its right side, and pressing the D key, it will stick and won't fall.

- Probably due to the script still adding velocity to the player, even when it is in air and colliding with an object

https://github.com/zamcham/scalatic-escape/assets/92247933/e929c03a-f50a-45c5-8ea4-d0d2149f6aa3

**Comment by zamcham** [comment]
Thank you! This has been fixed 👍
